# Generated by Django 3.2.3 on 2021-05-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privilege',
            field=models.IntegerField(default=1, verbose_name='Привелегия'),
        ),
    ]
