# Generated by Django 3.2.3 on 2021-05-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_user_privilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='privilege',
            field=models.CharField(choices=[('1', 'Учащийся'), ('2', 'Преподователь'), ('3', 'Администратор')], default=1, max_length=13, verbose_name='Привелегия'),
        ),
    ]
