# Generated by Django 3.2.3 on 2021-05-22 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_user_privilege'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='author',
        ),
        migrations.AddField(
            model_name='folder',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Преподователь'),
        ),
    ]
