# Generated by Django 3.2.3 on 2021-05-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20210522_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='specialty',
        ),
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.ManyToManyField(null=True, to='storage.Specialty', verbose_name='Специальность'),
        ),
    ]
