# Generated by Django 3.2.3 on 2021-05-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20210522_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initials',
            field=models.CharField(max_length=6, null=True, verbose_name='Инициалы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialty',
            field=models.ManyToManyField(to='storage.Specialty', verbose_name='Специальность'),
        ),
    ]
