# Generated by Django 3.2.3 on 2021-05-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20210522_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='initials',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Инициалы'),
        ),
    ]
