# Generated by Django 3.2.3 on 2021-05-23 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_folder_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.specialty', verbose_name='Специальность'),
        ),
    ]
