# Generated by Django 3.2.3 on 2021-05-23 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_file_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='specialty',
        ),
    ]
