# Generated by Django 3.2.3 on 2021-05-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_alter_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='hidden',
            field=models.BooleanField(default=0, verbose_name='Скрыт?'),
        ),
    ]
