# Generated by Django 3.2.3 on 2021-05-23 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_file_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialty',
            field=models.ManyToManyField(blank=True, to='storage.Specialty', verbose_name='Специальность'),
        ),
    ]
