# Generated by Django 3.2.3 on 2021-05-24 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_auto_20210523_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название папки')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('folder_ptr', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.folder', verbose_name='Родительская папка')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.specialty', verbose_name='Специальность')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Преподователь')),
            ],
            options={
                'verbose_name': 'Подпапка',
                'verbose_name_plural': 'Подпапки',
                'db_table': 'sub_folders',
                'ordering': ['title'],
            },
        ),
    ]
