# Generated by Django 3.2.3 on 2021-05-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0017_subfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='subfolder',
            name='hidden',
            field=models.BooleanField(default=0, verbose_name='Скрыта?'),
        ),
    ]
