# Generated by Django 3.2.3 on 2021-05-25 09:32

from django.db import migrations, models
import storage.models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0018_subfolder_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to=storage.models._user_directory_path, verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='title',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Название специльности'),
        ),
    ]
