# Generated by Django 3.2.3 on 2021-05-26 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0020_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder_ptr',
            field=models.IntegerField(null=True, verbose_name='Родительская папка'),
        ),
        migrations.AlterField(
            model_name='file',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='преподаватель'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='преподаватель'),
        ),
        migrations.AlterField(
            model_name='user',
            name='privilege',
            field=models.CharField(choices=[('1', 'Учащийся'), ('2', 'преподаватель'), ('3', 'Администратор')], default=1, max_length=13, verbose_name='Привелегия'),
        ),
        migrations.DeleteModel(
            name='SubFolder',
        ),
    ]
