# Generated by Django 3.2.3 on 2021-06-03 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0021_auto_20210526_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['title'], 'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.folder', verbose_name='Папка'),
        ),
        migrations.AlterField(
            model_name='file',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='folder_ptr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Родительская папка'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.specialty', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='title',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Название дисциплины'),
        ),
        migrations.AlterField(
            model_name='user',
            name='privilege',
            field=models.CharField(choices=[('1', 'Учащийся'), ('2', 'Преподаватель'), ('3', 'Администратор')], default=1, max_length=13, verbose_name='Привилегия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialty',
            field=models.ManyToManyField(blank=True, to='storage.Specialty', verbose_name='Дисциплина'),
        ),
    ]
