# Generated by Django 3.2.3 on 2021-06-05 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0022_auto_20210603_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.specialty', verbose_name='Дисциплина'),
        ),
    ]
